version: '3.6'
services:
  web:
    build: ./app
    environment:
    - db_host=postgres
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: "postgres:11"
    ports:
      - 5432:5432
    restart: always
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
